{{- if .Values.serviceAccount.create }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  {{- with .Values.serviceAccount }}
  name: {{ .name }}
  {{- if .annotations }}
  annotations:
{{ toYaml .annotations | indent 4 }}
  {{- end }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.serviceAccount.name }}
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["pods", "deployments", "deployments/scale", "jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.serviceAccount.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
{{- end }}
